name: Compile LaTeX

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: rapport.tex
          latexmk_use_xelatex: false
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: rapport
          path: rapport.pdf
          if-no-files-found: error
